projects:
  wizticketaws:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: 3cbinpo4sveehn2i7hwerjpc4m
      endpoints:
        prod: >-
          https://t6hraztefjdabgqzewgapjyicq.appsync-api.us-east-1.amazonaws.com/graphql
